<?xml version="1.0" encoding="utf-8"?><Database Name="BdYourFirstJob" Class="ConexionLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Function Name="dbo.InsertUsuario" Method="InsertUsuario">
    <Parameter Name="nombreUsuario" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="apellidos" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="correo" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="telefono" Type="System.Int32" DbType="Int" />
    <Parameter Name="fechaNacimiento" Type="System.DateTime" DbType="Date" />
    <Parameter Name="idRegion" Type="System.Int32" DbType="Int" />
    <Parameter Name="contrasena" Type="System.String" DbType="VarChar(255)" />
    <ElementType Name="InsertUsuarioResult">
      <Column Name="ErrorMessage" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>