#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yourFirstJobBack.AccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BdYourFirstJob")]
	public partial class LinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public LinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}

        public LinqDataContext() : this(@"Data Source=bdyourfirstjob.database.windows.net;Initial Catalog=BdYourFirstJob;Integrated Security=True")
        {
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ActualizarEmpresa")]
		public ISingleResult<ActualizarEmpresaResult> ActualizarEmpresa([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string nombreEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> telefonoEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cedulaJuridica, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idRegion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEmpresa, nombreEmpresa, telefonoEmpresa, cedulaJuridica, idRegion, descripcion);
			return ((ISingleResult<ActualizarEmpresaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarOfertaEmpleo")]
		public ISingleResult<InsertarOfertaEmpleoResult> InsertarOfertaEmpleo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string tituloEmpleo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string descripcionEmpleo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string ubicacionEmpleo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string tipoEmpleo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string experiencia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fechaPublicacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEmpresa, tituloEmpleo, descripcionEmpleo, ubicacionEmpleo, tipoEmpleo, experiencia, fechaPublicacion);
			return ((ISingleResult<InsertarOfertaEmpleoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertUsuario")]
		public ISingleResult<InsertUsuarioResult> InsertUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string nombreUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fechaNacimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idRegion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string contrasena)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreUsuario, apellidos, correo, telefono, fechaNacimiento, idRegion, contrasena);
			return ((ISingleResult<InsertUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ObtenerTodasLasOfertasEmpleo")]
		public ISingleResult<ObtenerTodasLasOfertasEmpleoResult> ObtenerTodasLasOfertasEmpleo()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ObtenerTodasLasOfertasEmpleoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ObtenerInformacionUsuario")]
		public ISingleResult<ObtenerInformacionUsuarioResult> ObtenerInformacionUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario);
			return ((ISingleResult<ObtenerInformacionUsuarioResult>)(result.ReturnValue));
		}
	}
	
	public partial class ActualizarEmpresaResult
	{
		
		private string _ErrorMessage;
		
		public ActualizarEmpresaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorMessage", DbType="NVarChar(4000)")]
		public string ErrorMessage
		{
			get
			{
				return this._ErrorMessage;
			}
			set
			{
				if ((this._ErrorMessage != value))
				{
					this._ErrorMessage = value;
				}
			}
		}
	}
	
	public partial class InsertarOfertaEmpleoResult
	{
		
		private string _ErrorMessage;
		
		public InsertarOfertaEmpleoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorMessage", DbType="NVarChar(4000)")]
		public string ErrorMessage
		{
			get
			{
				return this._ErrorMessage;
			}
			set
			{
				if ((this._ErrorMessage != value))
				{
					this._ErrorMessage = value;
				}
			}
		}
	}
	
	public partial class InsertUsuarioResult
	{
		
		private string _ErrorMessage;
		
		public InsertUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorMessage", DbType="NVarChar(4000)")]
		public string ErrorMessage
		{
			get
			{
				return this._ErrorMessage;
			}
			set
			{
				if ((this._ErrorMessage != value))
				{
					this._ErrorMessage = value;
				}
			}
		}
	}
	
	public partial class ObtenerTodasLasOfertasEmpleoResult
	{
		
		private int _idOfertas;
		
		private int _idEmpresa;
		
		private string _tituloEmpleo;
		
		private string _descripcionEmpleo;
		
		private string _ubicacionEmpleo;
		
		private string _tipoEmpleo;
		
		private string _experiencia;
		
		private System.DateTime _fechaPublicacion;
		
		public ObtenerTodasLasOfertasEmpleoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idOfertas", DbType="Int NOT NULL")]
		public int idOfertas
		{
			get
			{
				return this._idOfertas;
			}
			set
			{
				if ((this._idOfertas != value))
				{
					this._idOfertas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpresa", DbType="Int NOT NULL")]
		public int idEmpresa
		{
			get
			{
				return this._idEmpresa;
			}
			set
			{
				if ((this._idEmpresa != value))
				{
					this._idEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tituloEmpleo", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string tituloEmpleo
		{
			get
			{
				return this._tituloEmpleo;
			}
			set
			{
				if ((this._tituloEmpleo != value))
				{
					this._tituloEmpleo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcionEmpleo", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string descripcionEmpleo
		{
			get
			{
				return this._descripcionEmpleo;
			}
			set
			{
				if ((this._descripcionEmpleo != value))
				{
					this._descripcionEmpleo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ubicacionEmpleo", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string ubicacionEmpleo
		{
			get
			{
				return this._ubicacionEmpleo;
			}
			set
			{
				if ((this._ubicacionEmpleo != value))
				{
					this._ubicacionEmpleo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoEmpleo", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string tipoEmpleo
		{
			get
			{
				return this._tipoEmpleo;
			}
			set
			{
				if ((this._tipoEmpleo != value))
				{
					this._tipoEmpleo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_experiencia", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string experiencia
		{
			get
			{
				return this._experiencia;
			}
			set
			{
				if ((this._experiencia != value))
				{
					this._experiencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaPublicacion", DbType="Date NOT NULL")]
		public System.DateTime fechaPublicacion
		{
			get
			{
				return this._fechaPublicacion;
			}
			set
			{
				if ((this._fechaPublicacion != value))
				{
					this._fechaPublicacion = value;
				}
			}
		}
	}
	
	public partial class ObtenerInformacionUsuarioResult
	{
		
		private string _nombreUsuario;
		
		private string _apellidos;
		
		private string _correo;
		
		private int _telefono;
		
		private System.DateTime _fechaNacimiento;
		
		private string _sitioWeb;
		
		private string _nombreInstitucion;
		
		private string _gradoAcademico;
		
		private System.Nullable<System.DateTime> _fechaInicioEstudio;
		
		private System.Nullable<System.DateTime> _fechaFinEstudio;
		
		private string _nombreArchivo;
		
		private System.Data.Linq.Binary _archivo;
		
		private string _tipo;
		
		private string _categoria;
		
		private string _descripcion;
		
		private string _idioma;
		
		private string _nivel;
		
		private string _puestoLaboral;
		
		private string _nombreEmpresa;
		
		private string _responsabilidades;
		
		private System.Nullable<System.DateTime> _fechaInicioExperiencia;
		
		private System.Nullable<System.DateTime> _fechaFinExperiencia;
		
		public ObtenerInformacionUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreUsuario", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string nombreUsuario
		{
			get
			{
				return this._nombreUsuario;
			}
			set
			{
				if ((this._nombreUsuario != value))
				{
					this._nombreUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidos", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string apellidos
		{
			get
			{
				return this._apellidos;
			}
			set
			{
				if ((this._apellidos != value))
				{
					this._apellidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this._correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="Int NOT NULL")]
		public int telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this._telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaNacimiento", DbType="Date NOT NULL")]
		public System.DateTime fechaNacimiento
		{
			get
			{
				return this._fechaNacimiento;
			}
			set
			{
				if ((this._fechaNacimiento != value))
				{
					this._fechaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sitioWeb", DbType="VarChar(255)")]
		public string sitioWeb
		{
			get
			{
				return this._sitioWeb;
			}
			set
			{
				if ((this._sitioWeb != value))
				{
					this._sitioWeb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreInstitucion", DbType="VarChar(255)")]
		public string nombreInstitucion
		{
			get
			{
				return this._nombreInstitucion;
			}
			set
			{
				if ((this._nombreInstitucion != value))
				{
					this._nombreInstitucion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gradoAcademico", DbType="VarChar(255)")]
		public string gradoAcademico
		{
			get
			{
				return this._gradoAcademico;
			}
			set
			{
				if ((this._gradoAcademico != value))
				{
					this._gradoAcademico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaInicioEstudio", DbType="Date")]
		public System.Nullable<System.DateTime> fechaInicioEstudio
		{
			get
			{
				return this._fechaInicioEstudio;
			}
			set
			{
				if ((this._fechaInicioEstudio != value))
				{
					this._fechaInicioEstudio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaFinEstudio", DbType="Date")]
		public System.Nullable<System.DateTime> fechaFinEstudio
		{
			get
			{
				return this._fechaFinEstudio;
			}
			set
			{
				if ((this._fechaFinEstudio != value))
				{
					this._fechaFinEstudio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreArchivo", DbType="VarChar(255)")]
		public string nombreArchivo
		{
			get
			{
				return this._nombreArchivo;
			}
			set
			{
				if ((this._nombreArchivo != value))
				{
					this._nombreArchivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_archivo", DbType="VarBinary(MAX)", CanBeNull=true)]
		public System.Data.Linq.Binary archivo
		{
			get
			{
				return this._archivo;
			}
			set
			{
				if ((this._archivo != value))
				{
					this._archivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="VarChar(255)")]
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this._tipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoria", DbType="VarChar(255)")]
		public string categoria
		{
			get
			{
				return this._categoria;
			}
			set
			{
				if ((this._categoria != value))
				{
					this._categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(255)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idioma", DbType="VarChar(255)")]
		public string idioma
		{
			get
			{
				return this._idioma;
			}
			set
			{
				if ((this._idioma != value))
				{
					this._idioma = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nivel", DbType="VarChar(255)")]
		public string nivel
		{
			get
			{
				return this._nivel;
			}
			set
			{
				if ((this._nivel != value))
				{
					this._nivel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puestoLaboral", DbType="VarChar(255)")]
		public string puestoLaboral
		{
			get
			{
				return this._puestoLaboral;
			}
			set
			{
				if ((this._puestoLaboral != value))
				{
					this._puestoLaboral = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreEmpresa", DbType="VarChar(255)")]
		public string nombreEmpresa
		{
			get
			{
				return this._nombreEmpresa;
			}
			set
			{
				if ((this._nombreEmpresa != value))
				{
					this._nombreEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_responsabilidades", DbType="VarChar(255)")]
		public string responsabilidades
		{
			get
			{
				return this._responsabilidades;
			}
			set
			{
				if ((this._responsabilidades != value))
				{
					this._responsabilidades = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaInicioExperiencia", DbType="Date")]
		public System.Nullable<System.DateTime> fechaInicioExperiencia
		{
			get
			{
				return this._fechaInicioExperiencia;
			}
			set
			{
				if ((this._fechaInicioExperiencia != value))
				{
					this._fechaInicioExperiencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaFinExperiencia", DbType="Date")]
		public System.Nullable<System.DateTime> fechaFinExperiencia
		{
			get
			{
				return this._fechaFinExperiencia;
			}
			set
			{
				if ((this._fechaFinExperiencia != value))
				{
					this._fechaFinExperiencia = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
