#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yourFirstJobBackend.AccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BdYourFirstJob")]
	public partial class LinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public LinqDataContext() : 
				base(global::yourFirstJobBackend.Properties.Settings.Default.BdYourFirstJobConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarOfertaEmpleo")]
		public ISingleResult<InsertarOfertaEmpleoResult> InsertarOfertaEmpleo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string tituloEmpleo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string descripcionEmpleo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string ubicacionEmpleo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string tipoEmpleo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string experiencia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fechaPublicacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEmpresa, tituloEmpleo, descripcionEmpleo, ubicacionEmpleo, tipoEmpleo, experiencia, fechaPublicacion);
			return ((ISingleResult<InsertarOfertaEmpleoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertUsuario")]
		public ISingleResult<InsertUsuarioResult> InsertUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string nombreUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fechaNacimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idRegion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string contrasena, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorOccurred", DbType="Int")] ref System.Nullable<int> errorOccurred, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorMensaje", DbType="VarChar(255)")] ref string errorMensaje, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdReturn", DbType="Int")] ref System.Nullable<int> idReturn)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreUsuario, apellidos, correo, telefono, fechaNacimiento, idRegion, contrasena, errorOccurred, errorMensaje, idReturn);
			errorOccurred = ((System.Nullable<int>)(result.GetParameterValue(7)));
			errorMensaje = ((string)(result.GetParameterValue(8)));
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(9)));
			return ((ISingleResult<InsertUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ObtenerInformacionUsuario")]
		public ISingleResult<ObtenerInformacionUsuarioResult> ObtenerInformacionUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario);
			return ((ISingleResult<ObtenerInformacionUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BuscarOfertasEmpleoPorTitulo")]
		public ISingleResult<BuscarOfertasEmpleoPorTituloResult> BuscarOfertasEmpleoPorTitulo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string tituloEmpleo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tituloEmpleo);
			return ((ISingleResult<BuscarOfertasEmpleoPorTituloResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateUsuario")]
		public ISingleResult<UpdateUsuarioResult> UpdateUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string nombreUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fechaNacimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idRegion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string contrasena, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string sitioWeb)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, nombreUsuario, apellidos, correo, telefono, fechaNacimiento, idRegion, contrasena, sitioWeb);
			return ((ISingleResult<UpdateUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteUsuario")]
		public ISingleResult<DeleteUsuarioResult> DeleteUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario);
			return ((ISingleResult<DeleteUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Select_Idiomas_Oferta")]
		public ISingleResult<Select_Idiomas_OfertaResult> Select_Idiomas_Oferta([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idOferta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorOccurred", DbType="Int")] ref System.Nullable<int> errorOccurred, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorMensaje", DbType="VarChar(255)")] ref string errorMensaje)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idOferta, errorOccurred, errorMensaje);
			errorOccurred = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorMensaje = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<Select_Idiomas_OfertaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Select_Profeciones_Oferta")]
		public ISingleResult<Select_Profeciones_OfertaResult> Select_Profeciones_Oferta([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idOferta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorOccurred", DbType="Int")] ref System.Nullable<int> errorOccurred, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorMensaje", DbType="VarChar(255)")] ref string errorMensaje)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idOferta, errorOccurred, errorMensaje);
			errorOccurred = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorMensaje = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<Select_Profeciones_OfertaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Select_Habilidades_Oferta")]
		public ISingleResult<Select_Habilidades_OfertaResult> Select_Habilidades_Oferta([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idOferta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorOccurred", DbType="Int")] ref System.Nullable<int> errorOccurred, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorMensaje", DbType="VarChar(255)")] ref string errorMensaje)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idOferta, errorOccurred, errorMensaje);
			errorOccurred = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorMensaje = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<Select_Habilidades_OfertaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ObtenerTodasLasOfertasEmpleo")]
		public ISingleResult<ObtenerTodasLasOfertasEmpleoResult> ObtenerTodasLasOfertasEmpleo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorOccurred", DbType="Int")] ref System.Nullable<int> errorOccurred, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorMensaje", DbType="VarChar(255)")] ref string errorMensaje)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), errorOccurred, errorMensaje);
			errorOccurred = ((System.Nullable<int>)(result.GetParameterValue(0)));
			errorMensaje = ((string)(result.GetParameterValue(1)));
			return ((ISingleResult<ObtenerTodasLasOfertasEmpleoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InformacionUsuario")]
		public ISingleResult<SP_InformacionUsuarioResult> SP_InformacionUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorOccurred", DbType="Int")] ref System.Nullable<int> errorOccurred, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorMensaje", DbType="VarChar(255)")] ref string errorMensaje)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, errorOccurred, errorMensaje);
			errorOccurred = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorMensaje = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<SP_InformacionUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Select_Habilidad_Usuario")]
		public ISingleResult<Select_Habilidad_UsuarioResult> Select_Habilidad_Usuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorOccurred", DbType="Int")] ref System.Nullable<int> errorOccurred, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorMensaje", DbType="VarChar(255)")] ref string errorMensaje)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, errorOccurred, errorMensaje);
			errorOccurred = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorMensaje = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<Select_Habilidad_UsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Select_Estudios_Usuario")]
		public ISingleResult<Select_Estudios_UsuarioResult> Select_Estudios_Usuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorOccurred", DbType="Int")] ref System.Nullable<int> errorOccurred, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorMensaje", DbType="VarChar(255)")] ref string errorMensaje)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, errorOccurred, errorMensaje);
			errorOccurred = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorMensaje = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<Select_Estudios_UsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Select_Archivos_Usuario")]
		public ISingleResult<Select_Archivos_UsuarioResult> Select_Archivos_Usuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorOccurred", DbType="Int")] ref System.Nullable<int> errorOccurred, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorMensaje", DbType="VarChar(255)")] ref string errorMensaje)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, errorOccurred, errorMensaje);
			errorOccurred = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorMensaje = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<Select_Archivos_UsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Select_Experiencia_Laboral")]
		public ISingleResult<Select_Experiencia_LaboralResult> Select_Experiencia_Laboral([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorOccurred", DbType="Int")] ref System.Nullable<int> errorOccurred, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorMensaje", DbType="VarChar(255)")] ref string errorMensaje)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, errorOccurred, errorMensaje);
			errorOccurred = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorMensaje = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<Select_Experiencia_LaboralResult>)(result.ReturnValue));
		}
	}
	
	public partial class InsertarOfertaEmpleoResult
	{
		
		private string _ErrorMessage;
		
		public InsertarOfertaEmpleoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorMessage", DbType="NVarChar(4000)")]
		public string ErrorMessage
		{
			get
			{
				return this._ErrorMessage;
			}
			set
			{
				if ((this._ErrorMessage != value))
				{
					this._ErrorMessage = value;
				}
			}
		}
	}
	
	public partial class InsertUsuarioResult
	{
		
		private string _Message;
		
		public InsertUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="VarChar(27) NOT NULL", CanBeNull=false)]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this._Message = value;
				}
			}
		}
	}
	
	public partial class ObtenerInformacionUsuarioResult
	{
		
		private string _nombreUsuario;
		
		private string _apellidos;
		
		private string _correo;
		
		private int _telefono;
		
		private System.DateTime _fechaNacimiento;
		
		private string _sitioWeb;
		
		private string _nombreInstitucion;
		
		private string _gradoAcademico;
		
		private System.Nullable<System.DateTime> _fechaInicioEstudio;
		
		private System.Nullable<System.DateTime> _fechaFinEstudio;
		
		private string _nombreArchivo;
		
		private System.Data.Linq.Binary _archivo;
		
		private string _tipo;
		
		private string _categoria;
		
		private string _descripcion;
		
		private string _idioma;
		
		private string _nivel;
		
		private string _puestoLaboral;
		
		private string _nombreEmpresa;
		
		private string _responsabilidades;
		
		private System.Nullable<System.DateTime> _fechaInicioExperiencia;
		
		private System.Nullable<System.DateTime> _fechaFinExperiencia;
		
		public ObtenerInformacionUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreUsuario", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string nombreUsuario
		{
			get
			{
				return this._nombreUsuario;
			}
			set
			{
				if ((this._nombreUsuario != value))
				{
					this._nombreUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidos", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string apellidos
		{
			get
			{
				return this._apellidos;
			}
			set
			{
				if ((this._apellidos != value))
				{
					this._apellidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this._correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="Int NOT NULL")]
		public int telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this._telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaNacimiento", DbType="Date NOT NULL")]
		public System.DateTime fechaNacimiento
		{
			get
			{
				return this._fechaNacimiento;
			}
			set
			{
				if ((this._fechaNacimiento != value))
				{
					this._fechaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sitioWeb", DbType="VarChar(255)")]
		public string sitioWeb
		{
			get
			{
				return this._sitioWeb;
			}
			set
			{
				if ((this._sitioWeb != value))
				{
					this._sitioWeb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreInstitucion", DbType="VarChar(255)")]
		public string nombreInstitucion
		{
			get
			{
				return this._nombreInstitucion;
			}
			set
			{
				if ((this._nombreInstitucion != value))
				{
					this._nombreInstitucion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gradoAcademico", DbType="VarChar(255)")]
		public string gradoAcademico
		{
			get
			{
				return this._gradoAcademico;
			}
			set
			{
				if ((this._gradoAcademico != value))
				{
					this._gradoAcademico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaInicioEstudio", DbType="Date")]
		public System.Nullable<System.DateTime> fechaInicioEstudio
		{
			get
			{
				return this._fechaInicioEstudio;
			}
			set
			{
				if ((this._fechaInicioEstudio != value))
				{
					this._fechaInicioEstudio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaFinEstudio", DbType="Date")]
		public System.Nullable<System.DateTime> fechaFinEstudio
		{
			get
			{
				return this._fechaFinEstudio;
			}
			set
			{
				if ((this._fechaFinEstudio != value))
				{
					this._fechaFinEstudio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreArchivo", DbType="VarChar(255)")]
		public string nombreArchivo
		{
			get
			{
				return this._nombreArchivo;
			}
			set
			{
				if ((this._nombreArchivo != value))
				{
					this._nombreArchivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_archivo", DbType="VarBinary(MAX)", CanBeNull=true)]
		public System.Data.Linq.Binary archivo
		{
			get
			{
				return this._archivo;
			}
			set
			{
				if ((this._archivo != value))
				{
					this._archivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="VarChar(255)")]
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this._tipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoria", DbType="VarChar(255)")]
		public string categoria
		{
			get
			{
				return this._categoria;
			}
			set
			{
				if ((this._categoria != value))
				{
					this._categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(255)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idioma", DbType="VarChar(255)")]
		public string idioma
		{
			get
			{
				return this._idioma;
			}
			set
			{
				if ((this._idioma != value))
				{
					this._idioma = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nivel", DbType="VarChar(255)")]
		public string nivel
		{
			get
			{
				return this._nivel;
			}
			set
			{
				if ((this._nivel != value))
				{
					this._nivel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puestoLaboral", DbType="VarChar(255)")]
		public string puestoLaboral
		{
			get
			{
				return this._puestoLaboral;
			}
			set
			{
				if ((this._puestoLaboral != value))
				{
					this._puestoLaboral = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreEmpresa", DbType="VarChar(255)")]
		public string nombreEmpresa
		{
			get
			{
				return this._nombreEmpresa;
			}
			set
			{
				if ((this._nombreEmpresa != value))
				{
					this._nombreEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_responsabilidades", DbType="VarChar(255)")]
		public string responsabilidades
		{
			get
			{
				return this._responsabilidades;
			}
			set
			{
				if ((this._responsabilidades != value))
				{
					this._responsabilidades = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaInicioExperiencia", DbType="Date")]
		public System.Nullable<System.DateTime> fechaInicioExperiencia
		{
			get
			{
				return this._fechaInicioExperiencia;
			}
			set
			{
				if ((this._fechaInicioExperiencia != value))
				{
					this._fechaInicioExperiencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaFinExperiencia", DbType="Date")]
		public System.Nullable<System.DateTime> fechaFinExperiencia
		{
			get
			{
				return this._fechaFinExperiencia;
			}
			set
			{
				if ((this._fechaFinExperiencia != value))
				{
					this._fechaFinExperiencia = value;
				}
			}
		}
	}
	
	public partial class BuscarOfertasEmpleoPorTituloResult
	{
		
		private int _idOfertas;
		
		private int _idEmpresa;
		
		private string _tituloEmpleo;
		
		private string _descripcionEmpleo;
		
		private string _ubicacionEmpleo;
		
		private string _tipoEmpleo;
		
		private string _experiencia;
		
		private System.DateTime _fechaPublicacion;
		
		public BuscarOfertasEmpleoPorTituloResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idOfertas", DbType="Int NOT NULL")]
		public int idOfertas
		{
			get
			{
				return this._idOfertas;
			}
			set
			{
				if ((this._idOfertas != value))
				{
					this._idOfertas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpresa", DbType="Int NOT NULL")]
		public int idEmpresa
		{
			get
			{
				return this._idEmpresa;
			}
			set
			{
				if ((this._idEmpresa != value))
				{
					this._idEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tituloEmpleo", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string tituloEmpleo
		{
			get
			{
				return this._tituloEmpleo;
			}
			set
			{
				if ((this._tituloEmpleo != value))
				{
					this._tituloEmpleo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcionEmpleo", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string descripcionEmpleo
		{
			get
			{
				return this._descripcionEmpleo;
			}
			set
			{
				if ((this._descripcionEmpleo != value))
				{
					this._descripcionEmpleo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ubicacionEmpleo", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string ubicacionEmpleo
		{
			get
			{
				return this._ubicacionEmpleo;
			}
			set
			{
				if ((this._ubicacionEmpleo != value))
				{
					this._ubicacionEmpleo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoEmpleo", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string tipoEmpleo
		{
			get
			{
				return this._tipoEmpleo;
			}
			set
			{
				if ((this._tipoEmpleo != value))
				{
					this._tipoEmpleo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_experiencia", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string experiencia
		{
			get
			{
				return this._experiencia;
			}
			set
			{
				if ((this._experiencia != value))
				{
					this._experiencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaPublicacion", DbType="Date NOT NULL")]
		public System.DateTime fechaPublicacion
		{
			get
			{
				return this._fechaPublicacion;
			}
			set
			{
				if ((this._fechaPublicacion != value))
				{
					this._fechaPublicacion = value;
				}
			}
		}
	}
	
	public partial class UpdateUsuarioResult
	{
		
		private string _ErrorMessage;
		
		public UpdateUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorMessage", DbType="NVarChar(4000)")]
		public string ErrorMessage
		{
			get
			{
				return this._ErrorMessage;
			}
			set
			{
				if ((this._ErrorMessage != value))
				{
					this._ErrorMessage = value;
				}
			}
		}
	}
	
	public partial class DeleteUsuarioResult
	{
		
		private string _ErrorMessage;
		
		public DeleteUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorMessage", DbType="NVarChar(4000)")]
		public string ErrorMessage
		{
			get
			{
				return this._ErrorMessage;
			}
			set
			{
				if ((this._ErrorMessage != value))
				{
					this._ErrorMessage = value;
				}
			}
		}
	}
	
	public partial class Select_Idiomas_OfertaResult
	{
		
		private int _idIdioma;
		
		private string _idioma;
		
		private string _nivel;
		
		public Select_Idiomas_OfertaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idIdioma", DbType="Int NOT NULL")]
		public int idIdioma
		{
			get
			{
				return this._idIdioma;
			}
			set
			{
				if ((this._idIdioma != value))
				{
					this._idIdioma = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idioma", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string idioma
		{
			get
			{
				return this._idioma;
			}
			set
			{
				if ((this._idioma != value))
				{
					this._idioma = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nivel", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string nivel
		{
			get
			{
				return this._nivel;
			}
			set
			{
				if ((this._nivel != value))
				{
					this._nivel = value;
				}
			}
		}
	}
	
	public partial class Select_Profeciones_OfertaResult
	{
		
		private int _idProfesion;
		
		private string _nombreProfesion;
		
		private string _descripcion;
		
		public Select_Profeciones_OfertaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProfesion", DbType="Int NOT NULL")]
		public int idProfesion
		{
			get
			{
				return this._idProfesion;
			}
			set
			{
				if ((this._idProfesion != value))
				{
					this._idProfesion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreProfesion", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string nombreProfesion
		{
			get
			{
				return this._nombreProfesion;
			}
			set
			{
				if ((this._nombreProfesion != value))
				{
					this._nombreProfesion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
	}
	
	public partial class Select_Habilidades_OfertaResult
	{
		
		private int _idHabilidades;
		
		private string _categoria;
		
		private string _descripcion;
		
		public Select_Habilidades_OfertaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idHabilidades", DbType="Int NOT NULL")]
		public int idHabilidades
		{
			get
			{
				return this._idHabilidades;
			}
			set
			{
				if ((this._idHabilidades != value))
				{
					this._idHabilidades = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoria", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string categoria
		{
			get
			{
				return this._categoria;
			}
			set
			{
				if ((this._categoria != value))
				{
					this._categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
	}
	
	public partial class ObtenerTodasLasOfertasEmpleoResult
	{
		
		private int _idOfertas;
		
		private int _idEmpresa;
		
		private string _tituloEmpleo;
		
		private string _descripcionEmpleo;
		
		private string _ubicacionEmpleo;
		
		private string _tipoEmpleo;
		
		private string _experiencia;
		
		private System.DateTime _fechaPublicacion;
		
		private int _idEmpresa1;
		
		private string _nombreEmpresa;
		
		private int _telefonoEmpresa;
		
		private int _cedulaJuridica;
		
		private int _idRegion;
		
		private string _descripcion;
		
		private System.DateTime _fechaRegitro;
		
		private string _nombreRegion;
		
		public ObtenerTodasLasOfertasEmpleoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idOfertas", DbType="Int NOT NULL")]
		public int idOfertas
		{
			get
			{
				return this._idOfertas;
			}
			set
			{
				if ((this._idOfertas != value))
				{
					this._idOfertas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpresa", DbType="Int NOT NULL")]
		public int idEmpresa
		{
			get
			{
				return this._idEmpresa;
			}
			set
			{
				if ((this._idEmpresa != value))
				{
					this._idEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tituloEmpleo", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string tituloEmpleo
		{
			get
			{
				return this._tituloEmpleo;
			}
			set
			{
				if ((this._tituloEmpleo != value))
				{
					this._tituloEmpleo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcionEmpleo", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string descripcionEmpleo
		{
			get
			{
				return this._descripcionEmpleo;
			}
			set
			{
				if ((this._descripcionEmpleo != value))
				{
					this._descripcionEmpleo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ubicacionEmpleo", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string ubicacionEmpleo
		{
			get
			{
				return this._ubicacionEmpleo;
			}
			set
			{
				if ((this._ubicacionEmpleo != value))
				{
					this._ubicacionEmpleo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoEmpleo", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string tipoEmpleo
		{
			get
			{
				return this._tipoEmpleo;
			}
			set
			{
				if ((this._tipoEmpleo != value))
				{
					this._tipoEmpleo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_experiencia", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string experiencia
		{
			get
			{
				return this._experiencia;
			}
			set
			{
				if ((this._experiencia != value))
				{
					this._experiencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaPublicacion", DbType="Date NOT NULL")]
		public System.DateTime fechaPublicacion
		{
			get
			{
				return this._fechaPublicacion;
			}
			set
			{
				if ((this._fechaPublicacion != value))
				{
					this._fechaPublicacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpresa1", DbType="Int NOT NULL")]
		public int idEmpresa1
		{
			get
			{
				return this._idEmpresa1;
			}
			set
			{
				if ((this._idEmpresa1 != value))
				{
					this._idEmpresa1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreEmpresa", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string nombreEmpresa
		{
			get
			{
				return this._nombreEmpresa;
			}
			set
			{
				if ((this._nombreEmpresa != value))
				{
					this._nombreEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefonoEmpresa", DbType="Int NOT NULL")]
		public int telefonoEmpresa
		{
			get
			{
				return this._telefonoEmpresa;
			}
			set
			{
				if ((this._telefonoEmpresa != value))
				{
					this._telefonoEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedulaJuridica", DbType="Int NOT NULL")]
		public int cedulaJuridica
		{
			get
			{
				return this._cedulaJuridica;
			}
			set
			{
				if ((this._cedulaJuridica != value))
				{
					this._cedulaJuridica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRegion", DbType="Int NOT NULL")]
		public int idRegion
		{
			get
			{
				return this._idRegion;
			}
			set
			{
				if ((this._idRegion != value))
				{
					this._idRegion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaRegitro", DbType="DateTime NOT NULL")]
		public System.DateTime fechaRegitro
		{
			get
			{
				return this._fechaRegitro;
			}
			set
			{
				if ((this._fechaRegitro != value))
				{
					this._fechaRegitro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreRegion", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string nombreRegion
		{
			get
			{
				return this._nombreRegion;
			}
			set
			{
				if ((this._nombreRegion != value))
				{
					this._nombreRegion = value;
				}
			}
		}
	}
	
	public partial class SP_InformacionUsuarioResult
	{
		
		private int _idUsuario;
		
		private string _nombreUsuario;
		
		private string _apellidos;
		
		private string _correo;
		
		private int _telefono;
		
		private System.DateTime _fechaNacimiento;
		
		private int _idRegion;
		
		private string _contrasena;
		
		private string _sitioWeb;
		
		private System.DateTime _fechaRegitro;
		
		private int _idRegion1;
		
		private string _nombreRegion;
		
		private string _nombreRegion1;
		
		public SP_InformacionUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL")]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this._idUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreUsuario", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string nombreUsuario
		{
			get
			{
				return this._nombreUsuario;
			}
			set
			{
				if ((this._nombreUsuario != value))
				{
					this._nombreUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidos", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string apellidos
		{
			get
			{
				return this._apellidos;
			}
			set
			{
				if ((this._apellidos != value))
				{
					this._apellidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this._correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="Int NOT NULL")]
		public int telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this._telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaNacimiento", DbType="Date NOT NULL")]
		public System.DateTime fechaNacimiento
		{
			get
			{
				return this._fechaNacimiento;
			}
			set
			{
				if ((this._fechaNacimiento != value))
				{
					this._fechaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRegion", DbType="Int NOT NULL")]
		public int idRegion
		{
			get
			{
				return this._idRegion;
			}
			set
			{
				if ((this._idRegion != value))
				{
					this._idRegion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrasena", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string contrasena
		{
			get
			{
				return this._contrasena;
			}
			set
			{
				if ((this._contrasena != value))
				{
					this._contrasena = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sitioWeb", DbType="VarChar(255)")]
		public string sitioWeb
		{
			get
			{
				return this._sitioWeb;
			}
			set
			{
				if ((this._sitioWeb != value))
				{
					this._sitioWeb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaRegitro", DbType="DateTime NOT NULL")]
		public System.DateTime fechaRegitro
		{
			get
			{
				return this._fechaRegitro;
			}
			set
			{
				if ((this._fechaRegitro != value))
				{
					this._fechaRegitro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRegion1", DbType="Int NOT NULL")]
		public int idRegion1
		{
			get
			{
				return this._idRegion1;
			}
			set
			{
				if ((this._idRegion1 != value))
				{
					this._idRegion1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreRegion", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string nombreRegion
		{
			get
			{
				return this._nombreRegion;
			}
			set
			{
				if ((this._nombreRegion != value))
				{
					this._nombreRegion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreRegion1", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string nombreRegion1
		{
			get
			{
				return this._nombreRegion1;
			}
			set
			{
				if ((this._nombreRegion1 != value))
				{
					this._nombreRegion1 = value;
				}
			}
		}
	}
	
	public partial class Select_Habilidad_UsuarioResult
	{
		
		private int _idHabilidades;
		
		private string _categoria;
		
		private string _descripcion;
		
		public Select_Habilidad_UsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idHabilidades", DbType="Int NOT NULL")]
		public int idHabilidades
		{
			get
			{
				return this._idHabilidades;
			}
			set
			{
				if ((this._idHabilidades != value))
				{
					this._idHabilidades = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoria", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string categoria
		{
			get
			{
				return this._categoria;
			}
			set
			{
				if ((this._categoria != value))
				{
					this._categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
	}
	
	public partial class Select_Estudios_UsuarioResult
	{
		
		private int _idEstudios;
		
		private int _idUsuario;
		
		private string _nombreInstitucion;
		
		private string _gradoAcademico;
		
		private int _idProfesion;
		
		private System.DateTime _fechaInicio;
		
		private System.DateTime _fechaFinalizacion;
		
		public Select_Estudios_UsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEstudios", DbType="Int NOT NULL")]
		public int idEstudios
		{
			get
			{
				return this._idEstudios;
			}
			set
			{
				if ((this._idEstudios != value))
				{
					this._idEstudios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL")]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this._idUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreInstitucion", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string nombreInstitucion
		{
			get
			{
				return this._nombreInstitucion;
			}
			set
			{
				if ((this._nombreInstitucion != value))
				{
					this._nombreInstitucion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gradoAcademico", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string gradoAcademico
		{
			get
			{
				return this._gradoAcademico;
			}
			set
			{
				if ((this._gradoAcademico != value))
				{
					this._gradoAcademico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProfesion", DbType="Int NOT NULL")]
		public int idProfesion
		{
			get
			{
				return this._idProfesion;
			}
			set
			{
				if ((this._idProfesion != value))
				{
					this._idProfesion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaInicio", DbType="Date NOT NULL")]
		public System.DateTime fechaInicio
		{
			get
			{
				return this._fechaInicio;
			}
			set
			{
				if ((this._fechaInicio != value))
				{
					this._fechaInicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaFinalizacion", DbType="Date NOT NULL")]
		public System.DateTime fechaFinalizacion
		{
			get
			{
				return this._fechaFinalizacion;
			}
			set
			{
				if ((this._fechaFinalizacion != value))
				{
					this._fechaFinalizacion = value;
				}
			}
		}
	}
	
	public partial class Select_Archivos_UsuarioResult
	{
		
		private int _idArchivosUsuarios;
		
		private int _idUsuario;
		
		private string _nombreArchivo;
		
		private System.Data.Linq.Binary _archivo;
		
		private string _tipo;
		
		public Select_Archivos_UsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idArchivosUsuarios", DbType="Int NOT NULL")]
		public int idArchivosUsuarios
		{
			get
			{
				return this._idArchivosUsuarios;
			}
			set
			{
				if ((this._idArchivosUsuarios != value))
				{
					this._idArchivosUsuarios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL")]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this._idUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreArchivo", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string nombreArchivo
		{
			get
			{
				return this._nombreArchivo;
			}
			set
			{
				if ((this._nombreArchivo != value))
				{
					this._nombreArchivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_archivo", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false)]
		public System.Data.Linq.Binary archivo
		{
			get
			{
				return this._archivo;
			}
			set
			{
				if ((this._archivo != value))
				{
					this._archivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this._tipo = value;
				}
			}
		}
	}
	
	public partial class Select_Experiencia_LaboralResult
	{
		
		private int _idExperiencia;
		
		private int _idUsuario;
		
		private int _idProfesion;
		
		private string _puesto;
		
		private string _nombreEmpresa;
		
		private string _responsabilidades;
		
		private System.DateTime _fechaInicio;
		
		private System.DateTime _fechaFinalizacion;
		
		public Select_Experiencia_LaboralResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idExperiencia", DbType="Int NOT NULL")]
		public int idExperiencia
		{
			get
			{
				return this._idExperiencia;
			}
			set
			{
				if ((this._idExperiencia != value))
				{
					this._idExperiencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL")]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this._idUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProfesion", DbType="Int NOT NULL")]
		public int idProfesion
		{
			get
			{
				return this._idProfesion;
			}
			set
			{
				if ((this._idProfesion != value))
				{
					this._idProfesion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puesto", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string puesto
		{
			get
			{
				return this._puesto;
			}
			set
			{
				if ((this._puesto != value))
				{
					this._puesto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreEmpresa", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string nombreEmpresa
		{
			get
			{
				return this._nombreEmpresa;
			}
			set
			{
				if ((this._nombreEmpresa != value))
				{
					this._nombreEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_responsabilidades", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string responsabilidades
		{
			get
			{
				return this._responsabilidades;
			}
			set
			{
				if ((this._responsabilidades != value))
				{
					this._responsabilidades = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaInicio", DbType="Date NOT NULL")]
		public System.DateTime fechaInicio
		{
			get
			{
				return this._fechaInicio;
			}
			set
			{
				if ((this._fechaInicio != value))
				{
					this._fechaInicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaFinalizacion", DbType="Date NOT NULL")]
		public System.DateTime fechaFinalizacion
		{
			get
			{
				return this._fechaFinalizacion;
			}
			set
			{
				if ((this._fechaFinalizacion != value))
				{
					this._fechaFinalizacion = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
