<?xml version="1.0" encoding="utf-8"?><Database Name="BdYourFirstJob" Class="LinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=serverbdyourfirstjob.database.windows.net;Initial Catalog=BdYourFirstJob;Persist Security Info=True;User ID=nachogoyenaga;Encrypt=True" SettingsObjectName="yourFirstJobBackend.Properties.Settings" SettingsPropertyName="BdYourFirstJobConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.DeleteUsuario" Method="DeleteUsuario">
    <Parameter Name="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="ErrorOccurred" Parameter="errorOccurred" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ErrorMensaje" Parameter="errorMensaje" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <Parameter Name="LineasBorradas" Parameter="lineasBorradas" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="DeleteUsuarioResult">
      <Column Name="Message" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertarOfertaEmpleo" Method="InsertarOfertaEmpleo">
    <Parameter Name="idEmpresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="tituloEmpleo" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="descripcionEmpleo" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="ubicacionEmpleo" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="tipoEmpleo" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="experiencia" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="fechaPublicacion" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ErrorOccurred" Parameter="errorOccurred" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ErrorMensaje" Parameter="errorMensaje" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <Parameter Name="IdReturn" Parameter="idReturn" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ObtenerInformacionUsuario" Method="ObtenerInformacionUsuario">
    <Parameter Name="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="ErrorOccurred" Parameter="errorOccurred" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ErrorMensaje" Parameter="errorMensaje" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <ElementType Name="ObtenerInformacionUsuarioResult">
      <Column Name="nombreUsuario" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="apellidos" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="correo" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fechaNacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="sitioWeb" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="nombreInstitucion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="gradoAcademico" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="fechaInicioEstudio" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="fechaFinEstudio" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="nombreArchivo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="archivo" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" />
      <Column Name="tipo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="categoria" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="idioma" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="nivel" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="puestoLaboral" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="nombreEmpresa" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="responsabilidades" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="fechaInicioExperiencia" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="fechaFinExperiencia" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ObtenerTodasLasOfertasEmpleo" Method="ObtenerTodasLasOfertasEmpleo">
    <Parameter Name="ErrorOccurred" Parameter="errorOccurred" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ErrorMensaje" Parameter="errorMensaje" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <ElementType Name="ObtenerTodasLasOfertasEmpleoResult">
      <Column Name="idOfertas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idEmpresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tituloEmpleo" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="descripcionEmpleo" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ubicacionEmpleo" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="tipoEmpleo" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="experiencia" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="fechaPublicacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="idEmpresa1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombreEmpresa" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="telefonoEmpresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cedulaJuridica" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idRegion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="fechaRegitro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="nombreRegion" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Select_Habilidades_Oferta" Method="Select_Habilidades_Oferta">
    <Parameter Name="idOferta" Type="System.Int32" DbType="Int" />
    <Parameter Name="ErrorOccurred" Parameter="errorOccurred" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ErrorMensaje" Parameter="errorMensaje" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <ElementType Name="Select_Habilidades_OfertaResult">
      <Column Name="idHabilidades" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="categoria" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Select_Idiomas_Oferta" Method="Select_Idiomas_Oferta">
    <Parameter Name="idOferta" Type="System.Int32" DbType="Int" />
    <Parameter Name="ErrorOccurred" Parameter="errorOccurred" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ErrorMensaje" Parameter="errorMensaje" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <ElementType Name="Select_Idiomas_OfertaResult">
      <Column Name="idIdioma" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idioma" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="nivel" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Select_Profeciones_Oferta" Method="Select_Profeciones_Oferta">
    <Parameter Name="idOferta" Type="System.Int32" DbType="Int" />
    <Parameter Name="ErrorOccurred" Parameter="errorOccurred" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ErrorMensaje" Parameter="errorMensaje" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <ElementType Name="Select_Profeciones_OfertaResult">
      <Column Name="idProfesion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombreProfesion" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Select_Estudios_Usuario" Method="Select_Estudios_Usuario">
    <Parameter Name="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="ErrorOccurred" Parameter="errorOccurred" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ErrorMensaje" Parameter="errorMensaje" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <ElementType Name="Select_Estudios_UsuarioResult">
      <Column Name="idEstudios" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombreInstitucion" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="gradoAcademico" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="idProfesion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fechaInicio" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="fechaFinalizacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertUsuario" Method="InsertUsuario">
    <Parameter Name="nombreUsuario" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="apellidos" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="correo" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="telefono" Type="System.Int32" DbType="Int" />
    <Parameter Name="fechaNacimiento" Type="System.DateTime" DbType="Date" />
    <Parameter Name="idRegion" Type="System.Int32" DbType="Int" />
    <Parameter Name="contrasena" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="ErrorOccurred" Parameter="errorOccurred" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ErrorMensaje" Parameter="errorMensaje" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <Parameter Name="IdReturn" Parameter="idReturn" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="InsertUsuarioResult">
      <Column Name="Message" Type="System.String" DbType="VarChar(27) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.UpdateUsuario" Method="UpdateUsuario">
    <Parameter Name="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="nombreUsuario" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="apellidos" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="correo" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="telefono" Type="System.Int32" DbType="Int" />
    <Parameter Name="fechaNacimiento" Type="System.DateTime" DbType="Date" />
    <Parameter Name="idRegion" Type="System.Int32" DbType="Int" />
    <Parameter Name="contrasena" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="sitioWeb" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="ErrorOccurred" Parameter="errorOccurred" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ErrorMensaje" Parameter="errorMensaje" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <Parameter Name="CamposActualizados" Parameter="camposActualizados" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="UpdateUsuarioResult">
      <Column Name="Message" Type="System.String" DbType="VarChar(26) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_InformacionUsuario" Method="SP_InformacionUsuario">
    <Parameter Name="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="ErrorOccurred" Parameter="errorOccurred" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ErrorMensaje" Parameter="errorMensaje" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <ElementType Name="SP_InformacionUsuarioResult">
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombreUsuario" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="apellidos" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="correo" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fechaNacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="idRegion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="contrasena" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="sitioWeb" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="fechaRegitro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="idRegion1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombreRegion" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="nombreRegion1" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Select_Habilidad_Usuario" Method="Select_Habilidad_Usuario">
    <Parameter Name="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="ErrorOccurred" Parameter="errorOccurred" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ErrorMensaje" Parameter="errorMensaje" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <ElementType Name="Select_Habilidad_UsuarioResult">
      <Column Name="idHabilidades" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="categoria" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Select_Experiencia_Laboral" Method="Select_Experiencia_Laboral">
    <Parameter Name="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="ErrorOccurred" Parameter="errorOccurred" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ErrorMensaje" Parameter="errorMensaje" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <ElementType Name="Select_Experiencia_LaboralResult">
      <Column Name="idExperiencia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idProfesion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="puesto" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="nombreEmpresa" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="responsabilidades" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="fechaInicio" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="fechaFinalizacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Select_Archivos_Usuario" Method="Select_Archivos_Usuario">
    <Parameter Name="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="ErrorOccurred" Parameter="errorOccurred" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ErrorMensaje" Parameter="errorMensaje" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <ElementType Name="Select_Archivos_UsuarioResult">
      <Column Name="idArchivosUsuarios" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombreArchivo" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="archivo" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="tipo" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Select_Estudios_Usuario" Method="Select_Estudios_Usuario1">
    <Parameter Name="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="ErrorOccurred" Parameter="errorOccurred" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ErrorMensaje" Parameter="errorMensaje" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <ElementType Name="Select_Estudios_UsuarioResult1">
      <Column Name="idEstudios" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombreInstitucion" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="gradoAcademico" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="idProfesion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fechaInicio" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="fechaFinalizacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Select_Archivos_Oferta" Method="Select_Archivos_Oferta">
    <Parameter Name="idOferta" Type="System.Int32" DbType="Int" />
    <Parameter Name="ErrorOccurred" Parameter="errorOccurred" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ErrorMensaje" Parameter="errorMensaje" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <ElementType Name="Select_Archivos_OfertaResult">
      <Column Name="idArchivosOferta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idOfertas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombreArchivo" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="archivo" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="tipo" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.BuscarOfertasEmpleoPorTitulo" Method="BuscarOfertasEmpleoPorTitulo">
    <Parameter Name="tituloEmpleo" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="ErrorOccurred" Parameter="errorOccurred" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ErrorMensaje" Parameter="errorMensaje" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <ElementType Name="BuscarOfertasEmpleoPorTituloResult">
      <Column Name="idOfertas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idEmpresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tituloEmpleo" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="descripcionEmpleo" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ubicacionEmpleo" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="tipoEmpleo" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="experiencia" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="fechaPublicacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="idEmpresa1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombreEmpresa" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="telefonoEmpresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cedulaJuridica" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idRegion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="fechaRegitro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="nombreRegion" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Actualizar_Habilidades_Usuario" Method="Actualizar_Habilidades_Usuario">
    <Parameter Name="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="categoria" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="descripcion" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="ErrorOccurred" Parameter="errorOccurred" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ErrorMensaje" Parameter="errorMensaje" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <Parameter Name="CamposActualizados" Parameter="camposActualizados" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="Actualizar_Habilidades_UsuarioResult">
      <Column Name="Message" Type="System.String" DbType="VarChar(35) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Actualizar_Idiomas_Usuario" Method="Actualizar_Idiomas_Usuario">
    <Parameter Name="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="idioma" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="nivel" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="ErrorOccurred" Parameter="errorOccurred" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ErrorMensaje" Parameter="errorMensaje" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <Parameter Name="CamposActualizados" Parameter="camposActualizados" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="Actualizar_Idiomas_UsuarioResult">
      <Column Name="Message" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Actualizar_Usuario_Relaciones" Method="Actualizar_Usuario_Relaciones">
    <Parameter Name="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="nombreUsuario" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="apellidos" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="correo" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="telefono" Type="System.Int32" DbType="Int" />
    <Parameter Name="fechaNacimiento" Type="System.DateTime" DbType="Date" />
    <Parameter Name="idRegion" Type="System.Int32" DbType="Int" />
    <Parameter Name="contrasena" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="sitioWeb" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="idioma" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="nivel" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="categoria" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="descripcion" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="ErrorOccurred" Parameter="errorOccurred" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ErrorMensaje" Parameter="errorMensaje" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <ElementType Name="Actualizar_Usuario_RelacionesResult">
      <Column Name="Message" Type="System.String" DbType="VarChar(34) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Login_User" Method="Login_User">
    <Parameter Name="username" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="ErrorOccurred" Parameter="errorOccurred" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ErrorMensaje" Parameter="errorMensaje" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <Parameter Name="idReturn" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="Login_UserResult">
      <Column Name="Message" Type="System.String" DbType="VarChar(44) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>